### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by whwh747** [umautobots/LONER#16]
![6618367dc7a053e7b73f1141a6bd229](https://github.com/user-attachments/assets/1cd6118f-a028-46f6-8c13-38c721ae1bef)

**Comment by whwh747** [comment]
Thank you for your excellent work. Could you please explain why I'm unable to pull the Docker image?

**Comment by sethgi** [comment]
Unfortunately this seems to happen here and there. Could you let me know where you are located? I’m trying to figure out why this happens to only some users.

please see this answer for instructions on building the container from source. It’s a bit time consuming which is why I provided the built image. https://github.com/umautobots/LONER/issues/13#issuecomment-1887566989

**Comment by whwh747** [comment]
![86d04fb3fe592b9879a5f3f5abc4239](https://github.com/user-attachments/assets/db492294-3b3d-4cf2-909e-f274bbf2bead)

**Comment by whwh747** [comment]
China

**Comment by whwh747** [comment]
Since I haven't used Docker before, I'm not sure what the issue is. Could it be a network problem?

**Comment by whwh747** [comment]
I encountered an error when building the container from the source code, as shown in the image above. Could you please advise me on how to resolve this issue? I would be very grateful for your assistance. @sethgi

**Comment by sethgi** [comment]
this is a problem you're running into with Dockerhub, which has issues in China.

This is a somewhat known issue: https://github.com/docker/hub-feedback/issues/2388

So unfortunately I can't really help... if you can't pull the nvidia docker images, there's not much I can do. In the future I may look into hosting our image somewhere else, but that's not something I can do at the moment. Sorry.

**Comment by whwh747** [comment]
thank you!
