### ISSUE TITLE
Why not use RGB images?

### ISSUE THREAD

**Issue by akawincent** [umautobots/LONER#7]
I saw that there are many variables and functions related to RGB images in code.
Therefore, I reasonably infer that you have tried to combine RGB and LiDAR sensor data to design nerf-based slam.
So why did you only use Lidar data in the end?
Is it because the effect after fusing RGB and LiDAR  is not much improved?

Looking forward to your reply!

**Comment by sethgi** [comment]
Thanks for the question!

The short answer is that our primary focus for this version was geometric accuracy. Introducing RGB data is a potential avenue of future investigation, but it wasn't a priority for this version. We don't expect RGB data to improve geometric accuracy, though there could be some benefits because we could produce realistic RGB renders, which we cannot currently do.

Extending our method to fuse RGB data (for example with a method similar to https://arxiv.org/abs/2209.01194) remains an exciting area for future work.

However, due to the fact that we aim to test in larger-scale environments than most existing implicit SLAM methods and we are unwilling to compromise on real-time performance, we think this will be relatively non-trivial to make work well and fast enough to remain real-time.
